#!/bin/sh -e
# Copyright 2023 Oliver Smith
# SPDX-License-Identifier: GPL-3.0-or-later
# Description: lint all shell scripts and APKBUILDs
# https://postmarketos.org/pmb-ci

if [ "$(id -u)" = 0 ]; then
	set -x
	apk -q add shellcheck
	exec su "${TESTUSER:-build}" -c "sh -e $0"
fi

# Check all shell scripts and APKBUILDS that are not in the cross directory
# because cross is autogenerated and not in device/archived because they are
# not updated.
sh_files="$(\
	find . \
	-name '*.sh' \
	-not -path '*cross/*' \
	-not -path '*device/archived/*' \
	-o -name 'APKBUILD' \
	-not -path '*cross/*' \
	-not -path '*device/archived/*'
	)"

# Set the shell to Busybox ash.
shellcheck_args="${shellcheck_args} -s busybox"
# sc3036: Allow the `-e` argument to `echo`.
shellcheck_args="${shellcheck_args} -e SC3036"
# sc3045: Allow the `-t` argument to `type`.
shellcheck_args="${shellcheck_args} -e SC3045"
# -x: Support sources outside of the file. 
shellcheck_args="${shellcheck_args} -x"

for file in $sh_files; do
	if [ "${file##*/}" = 'APKBUILD' ]; then
		# sc2148: Allow missing shbang as APKBUILDs are not executed directly.
		shellcheck_args="${shellcheck_args} -e SC2148"
		# sc2034: Allow unused variables as most are parsed by abuild.
		shellcheck_args="${shellcheck_args} -e SC2034"
		# sc2154: Allow unused variables as most come from abuild.
		shellcheck_args="${shellcheck_args} -e SC2154"
		# sc1091: Allow the usage of our packaging variables.
		# (e.g. downstreamkernel_prepare)
		shellcheck_args="${shellcheck_args} -e SC1091"
	fi
	echo "Test with shellcheck: $file"
	eval "$(which shellcheck) ${shellcheck_args} ${file}"
done
